Kamu 165 set watermark  add event from UI
kamu-data/kamu-web-ui pull request #105
Opened 2023-06-07 15:35 UTC by dmitriy-borzenko

2023-06-11 14:46 UTC, zaychenko-sergei requested changes
Perhaps we also need this edit link on Metadata tab:

![image](https://github.com/kamu-data/kamu-web-ui/assets/8875909/9ea10aab-be38-42cf-b019-4d3bc070d0b8)

2023-06-11 14:46 UTC, zaychenko-sergei commented on src/app/dataset-view/additional-components/overview-component/components/edit-watermark-modal/edit-watermark-modal.component.ts
> +    public tooltip = "Description of the watermark.";
readonly, uppercase

2023-06-11 14:46 UTC, zaychenko-sergei commented on src/app/dataset-view/additional-components/overview-component/overview-component.html
> +                        *ngIf="currentState.overview.kind==='ROOT'"
I am not sure this condition is valid. Why do you think this should be disallowed for derived datasets?

2023-06-12 09:31 UTC, dmitriy-borzenko commented on src/app/dataset-view/additional-components/overview-component/components/edit-watermark-modal/edit-watermark-modal.component.ts
> +    public tooltip = "Description of the watermark.";
Deleted this property

2023-06-13 07:09 UTC, zaychenko-sergei commented on src/app/dataset-view/additional-components/overview-component/overview-component.ts
> +        ).currentWatermark = this.currentState?.overview.metadata
Maybe do this cast just once?

2023-06-13 15:29 UTC, zaychenko-sergei commented
Don't forget Changelog entry

2023-06-13 17:20 UTC, merged