Kamu UI 192 small style improvements
kamu-data/kamu-web-ui pull request #197
Opened 2023-10-13 17:56 UTC by dmitriy-borzenko

2023-10-16 09:22 UTC, zaychenko-sergei commented on src/app/auth/account/account.component.spec.ts
> +    it("should check activeTab when URL not exist query param tab", fakeAsync(() => {
Why `fakeAsync`? I don't see any ticks or flush

2023-10-16 18:36 UTC, dmitriy-borzenko commented on src/app/auth/account/account.component.spec.ts
> +    it("should check activeTab when URL not exist query param tab", fakeAsync(() => {
Removed

2023-10-17 08:49 UTC, EvilAlexei approved these changes

2023-10-17 09:12 UTC, zaychenko-sergei commented on src/app/auth/account/account.component.html
> +                        disabled="true"
I can see you've added these attributes, but the tabs are stil clickable for some reason

2023-10-17 09:13 UTC, zaychenko-sergei requested changes
The following requirement is not covered:

Use correct account avatar in data preview:
![image](https://github.com/kamu-data/kamu-web-ui/assets/8875909/88049f63-2045-4e7e-a02a-479bb60c2840)

I can see Kamu picture in all configurations.

2023-10-17 18:27 UTC, dmitriy-borzenko commented
> The following requirement is not covered:
> 
> Use correct account avatar in data preview: ![image](https://user-images.githubusercontent.com/8875909/275778082-88049f63-2045-4e7e-a02a-479bb60c2840.png)
> 
> I can see Kamu picture in all configurations.

Fixed

2023-10-18 14:23 UTC, zaychenko-sergei commented on src/app/components/lineage-graph/lineage-graph.component.ts
> +        return screen.height - 390;
It's architecturally incorrect for middle-layer component to assume a certain environment in higher level components in the hierarchy. It should be getting the computed number through @Input port. Only the main component `AppComponent` is aware of where header exists. Only `DatasetComponent` knows about dataset tabs. `LineageGraphComponent` is not allowed to access this information.

2023-10-18 14:24 UTC, zaychenko-sergei commented on src/app/components/lineage-graph/lineage-graph.component.ts
> +        return screen.height - 390;
Plz report a separate ticket for this problem, and revert to constant for now.

2023-10-18 14:34 UTC, zaychenko-sergei approved these changes

2023-10-18 14:47 UTC, merged